# Cloud Build configuration for Invoice Processing Pipeline
# Builds and deploys all 4 Cloud Run functions
#
# Usage (from project root):
#   gcloud builds submit --config functions/gcp/v1/cloudbuild.yaml functions/gcp/v1
#
# Usage (from this directory):
#   gcloud builds submit --config cloudbuild.yaml .
#
# Required substitutions:
#   _REGION: GCP region (default: us-central1)

substitutions:
  _REGION: us-central1
  _INPUT_BUCKET: ${PROJECT_ID}-invoices-input
  _PROCESSED_BUCKET: ${PROJECT_ID}-invoices-processed
  _ARCHIVE_BUCKET: ${PROJECT_ID}-invoices-archive
  _FAILED_BUCKET: ${PROJECT_ID}-invoices-failed
  _UPLOADED_TOPIC: invoice-uploaded
  _CONVERTED_TOPIC: invoice-converted
  _CLASSIFIED_TOPIC: invoice-classified
  _EXTRACTED_TOPIC: invoice-extracted
  _BQ_DATASET: invoices
  _GEMINI_MODEL: gemini-2.0-flash-exp

steps:
  # Build and deploy tiff-to-png-converter
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-tiff-to-png'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tiff-to-png-converter:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tiff-to-png-converter:latest'
      - '-f'
      - 'deploy/tiff_to_png.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-tiff-to-png'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tiff-to-png-converter:$COMMIT_SHA'
    waitFor: ['build-tiff-to-png']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-tiff-to-png'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tiff-to-png-converter'
      - '--image=gcr.io/$PROJECT_ID/tiff-to-png-converter:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--memory=1Gi'
      - '--timeout=300'
      - '--no-allow-unauthenticated'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_REGION=$_REGION,INPUT_BUCKET=$_INPUT_BUCKET,PROCESSED_BUCKET=$_PROCESSED_BUCKET,CONVERTED_TOPIC=$_CONVERTED_TOPIC'
    waitFor: ['push-tiff-to-png']

  # Build and deploy invoice-classifier
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-classifier'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/invoice-classifier:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/invoice-classifier:latest'
      - '-f'
      - 'deploy/invoice_classifier.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-classifier'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/invoice-classifier:$COMMIT_SHA'
    waitFor: ['build-classifier']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-classifier'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'invoice-classifier'
      - '--image=gcr.io/$PROJECT_ID/invoice-classifier:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--memory=1Gi'
      - '--timeout=300'
      - '--no-allow-unauthenticated'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_REGION=$_REGION,PROCESSED_BUCKET=$_PROCESSED_BUCKET,ARCHIVE_BUCKET=$_ARCHIVE_BUCKET,CLASSIFIED_TOPIC=$_CLASSIFIED_TOPIC'
    waitFor: ['push-classifier']

  # Build and deploy data-extractor
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-extractor'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/data-extractor:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/data-extractor:latest'
      - '-f'
      - 'deploy/data_extractor.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-extractor'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/data-extractor:$COMMIT_SHA'
    waitFor: ['build-extractor']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-extractor'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'data-extractor'
      - '--image=gcr.io/$PROJECT_ID/data-extractor:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--timeout=540'
      - '--no-allow-unauthenticated'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_REGION=$_REGION,PROCESSED_BUCKET=$_PROCESSED_BUCKET,FAILED_BUCKET=$_FAILED_BUCKET,EXTRACTED_TOPIC=$_EXTRACTED_TOPIC,GEMINI_MODEL=$_GEMINI_MODEL'
    waitFor: ['push-extractor']

  # Build and deploy bigquery-writer
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-writer'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bigquery-writer:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bigquery-writer:latest'
      - '-f'
      - 'deploy/bigquery_writer.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-writer'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bigquery-writer:$COMMIT_SHA'
    waitFor: ['build-writer']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-writer'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bigquery-writer'
      - '--image=gcr.io/$PROJECT_ID/bigquery-writer:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--memory=512Mi'
      - '--timeout=120'
      - '--no-allow-unauthenticated'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GCP_REGION=$_REGION,BQ_DATASET=$_BQ_DATASET'
    waitFor: ['push-writer']

images:
  - 'gcr.io/$PROJECT_ID/tiff-to-png-converter:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tiff-to-png-converter:latest'
  - 'gcr.io/$PROJECT_ID/invoice-classifier:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/invoice-classifier:latest'
  - 'gcr.io/$PROJECT_ID/data-extractor:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/data-extractor:latest'
  - 'gcr.io/$PROJECT_ID/bigquery-writer:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/bigquery-writer:latest'

options:
  logging: CLOUD_LOGGING_ONLY
